### ISSUE TITLE
Is OpenCV built?

### ISSUE THREAD

**Issue by kxygk** [hellonico/origami-box#1]
I've never used `vagrant` but `origami-box/provisioning/build-opencv.sh`  seems to just clone the repo but not build it?

Is this WIP?

**Comment by hellonico** [comment]
@geokon-gh  that's correct. no its not build ... that was the box I created to do testing yesterday. you need something in particular ?

**Comment by kxygk** [comment]
Nope! Sorry. So it was built manually. You just pointed me here from the other issue so I thought I missed something. I'll try to look into having OpenCV built from withing Lein once I wrap my head around it a bit better

**Comment by hellonico** [comment]
Ah .. I see! You wanted to refer to your own custom build of opencv and use it with origami right ? (using custom flags??) 

I have bits around to do this and I can gather the scripts to create a linux only jar file (or maybe even a osx jar file) that gets installed into your local maven repository, and then you could refer to that in the template. 

The thing is obviously to use the same version of opencv as the origami wrapper was generated with... otherwise some hard core dump are to be excepted.

I'll add the script probably later on this week.

As a brief overview though, to generate a jar file for all plateforms, I manually kick a build of opencv on each plateforms (linux32,linux64,osx,windows) and then generate the different  native jar files and upload them to my repository. The opencv-native 3.3.1_4 includes all 4 native libraries to make it portable. 

Does that make sense ?

**Comment by kxygk** [comment]
Okay, I gotcha. So as the number of platforms grows this will get larger and larger. You can't just have Maven/Lein kick off a CMake process to build your jar? CMake should run no-problem on every platform. Or maybe download the prebuilt stuff when the platform is Windows and run CMake otherwise? I don't really personally need this right now (though I do run Debian on ARM sometimes) - but I don't think the linux lib will work on all distros b/c of glib mismatches

Anyways, as far as I'm concerned - everything works for me and I'm happy :)
